import { NextRequest, NextResponse } from 'next/server'
import { createClient } from '@/lib/supabase/server'
import { Resend } from 'resend'
import { sanitize, safeError } from '@/lib/validation'

export async function POST(req: NextRequest) {
  try {
    const supabase = createClient()
    const { data: { user } } = await supabase.auth.getUser()
    if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

    const body = await req.json()
    const letterContent = sanitize(body.letterContent ?? '', 20000)
    const letterTitle = sanitize(body.letterTitle ?? 'Your Dispute Letter', 200)
    const recipientEmail = user.email

    if (!letterContent || !recipientEmail) {
      return NextResponse.json({ error: 'Missing required fields' }, { status: 400 })
    }

    const resend = new Resend(process.env.RESEND_API_KEY)

    const htmlContent = `
      <!DOCTYPE html>
      <html>
        <head>
          <meta charset="utf-8">
          <style>
            body { font-family: Georgia, serif; color: #1a1a2e; background: #f5f5f5; margin: 0; padding: 20px; }
            .container { max-width: 700px; margin: 0 auto; background: white; border-radius: 8px; overflow: hidden; box-shadow: 0 2px 8px rgba(0,0,0,0.1); }
            .header { background: #1a1a2e; padding: 24px 32px; }
            .header-title { color: #2dd4bf; font-size: 20px; font-weight: bold; margin: 0; }
            .header-sub { color: rgba(255,255,255,0.6); font-size: 13px; margin: 4px 0 0; }
            .letter-title { background: #f8fafc; padding: 16px 32px; border-bottom: 1px solid #e2e8f0; }
            .letter-title h2 { margin: 0; font-size: 16px; color: #334155; }
            .content { padding: 32px; }
            .letter-body { white-space: pre-wrap; font-size: 14px; line-height: 1.7; color: #1e293b; font-family: 'Courier New', monospace; background: #f8fafc; padding: 24px; border-radius: 6px; border: 1px solid #e2e8f0; }
            .footer { padding: 20px 32px; background: #f8fafc; border-top: 1px solid #e2e8f0; font-size: 12px; color: #94a3b8; }
            .tip { background: #ecfdf5; border-left: 3px solid #2dd4bf; padding: 12px 16px; margin-bottom: 20px; border-radius: 0 6px 6px 0; font-size: 13px; color: #047857; }
          </style>
        </head>
        <body>
          <div class="container">
            <div class="header">
              <p class="header-title">⚡ DebtCoach AI</p>
              <p class="header-sub">Your dispute letter is ready to send</p>
            </div>
            <div class="letter-title">
              <h2>${letterTitle}</h2>
            </div>
            <div class="content">
              <div class="tip">
                <strong>Next step:</strong> Print this letter and mail it via <strong>Certified Mail with Return Receipt</strong> to the bureau's address shown in the letter. Keep your receipt as proof.
              </div>
              <div class="letter-body">${letterContent.replace(/</g, '&lt;').replace(/>/g, '&gt;')}</div>
            </div>
            <div class="footer">
              Generated by DebtCoach AI &bull; thedebtcoachai.com &bull; This letter is for your personal use. DebtCoach AI is not a law firm and this is not legal advice.
            </div>
          </div>
        </body>
      </html>
    `

    const { data, error } = await resend.emails.send({
      from: 'DebtCoach AI <letters@thedebtcoachai.com>',
      to: [recipientEmail],
      subject: `Your Letter: ${letterTitle}`,
      html: htmlContent,
    })

    if (error) {
      console.error('Resend error:', error)
      return NextResponse.json({ error: 'Failed to send email' }, { status: 500 })
    }

    return NextResponse.json({ success: true, messageId: data?.id })
  } catch (err: any) {
    return safeError(err, 'email-letter')
  }
}
