import Link from 'next/link'
import { Zap } from 'lucide-react'

export const metadata = {
  title: 'Terms of Service | DebtCoach AI',
  description: 'Terms of Service for DebtCoach AI — please read carefully before using the service.',
}

const EFFECTIVE_DATE = 'April 25, 2026'
const COMPANY_NAME = 'DebtCoach AI LLC'
const COMPANY_EMAIL = 'support@thedebtcoachai.com'
const GOVERNING_STATE = 'Texas'
const ARBITRATION_NOTICE_ADDRESS = 'support@thedebtcoachai.com'

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-navy-200 text-white">
      {/* Nav */}
      <nav className="fixed top-0 left-0 right-0 z-50 border-b border-white/10 backdrop-blur-md bg-navy-200/90">
        <div className="max-w-6xl mx-auto px-4 py-4 flex items-center justify-between">
          <Link href="/" className="flex items-center gap-2.5">
            <div className="w-8 h-8 bg-teal-400 rounded-xl flex items-center justify-center">
              <Zap className="w-4 h-4 text-navy-200" />
            </div>
            <span className="font-bold text-white">DebtCoach AI</span>
          </Link>
          <Link href="/auth/login" className="text-white/60 hover:text-white text-sm font-medium transition-colors">
            Sign In
          </Link>
        </div>
      </nav>

      <main className="max-w-3xl mx-auto px-4 pt-28 pb-20">
        {/* Header */}
        <div className="mb-10">
          <h1 className="text-4xl font-extrabold text-white mb-3">Terms of Service</h1>
          <p className="text-white/40 text-sm">Effective Date: {EFFECTIVE_DATE}</p>
        </div>

        {/* Arbitration Banner — must be prominent */}
        <div className="bg-yellow-400/10 border-2 border-yellow-400/40 rounded-2xl p-6 mb-10">
          <p className="text-yellow-300 font-bold text-sm uppercase tracking-wide mb-2">
            ⚠ Important Notice Regarding Your Legal Rights
          </p>
          <p className="text-white/80 text-sm leading-relaxed">
            <strong>These Terms contain a binding arbitration agreement and class action waiver in Section 15.</strong> By
            using DebtCoach AI you agree that disputes will be resolved by individual binding arbitration rather than in
            court, and you waive your right to a jury trial and to participate in class, collective, or representative
            actions. You may opt out of arbitration within 30 days of first use — see Section 15.8.
          </p>
        </div>

        <div className="prose prose-invert prose-sm max-w-none space-y-8 text-white/70 leading-relaxed">

          {/* 1 */}
          <section>
            <h2 className="text-white text-xl font-bold mb-3">1. Agreement to Terms</h2>
            <p>
              These Terms of Service (&quot;Terms&quot;) constitute a legally binding agreement between you (&quot;User,&quot; &quot;you,&quot; or
              &quot;your&quot;) and {COMPANY_NAME} (&quot;Company,&quot; &quot;we,&quot; &quot;us,&quot; or &quot;our&quot;) governing your access to and use of
              the DebtCoach AI platform, website, and all related services (collectively, the &quot;Service&quot;).
            </p>
            <p className="mt-3">
              BY ACCESSING OR USING THE SERVICE, CREATING AN ACCOUNT, OR CLICKING &quot;I AGREE,&quot; YOU ACKNOWLEDGE THAT
              YOU HAVE READ, UNDERSTOOD, AND AGREE TO BE BOUND BY THESE TERMS IN THEIR ENTIRETY. IF YOU DO NOT
              AGREE, DO NOT ACCESS OR USE THE SERVICE.
            </p>
            <p className="mt-3">
              If you are using the Service on behalf of an organization, you represent and warrant that you have the
              authority to bind that organization to these Terms.
            </p>
          </section>

          {/* 2 */}
          <section>
            <h2 className="text-white text-xl font-bold mb-3">2. Not Legal Advice — Educational Service Only</h2>
            <p>
              DebtCoach AI is an <strong className="text-white">educational information service only</strong>. The Service
              does not provide legal advice, legal representation, or legal services of any kind. The Company is not a
              law firm. No attorney-client relationship is created by your use of the Service.
            </p>
            <p className="mt-3">
              All content generated by or through the Service — including AI-generated responses, letter templates,
              rights summaries, conversation guides, and any other materials — is provided solely for general educational
              and informational purposes. Such content does not constitute legal advice and may not apply to your
              specific situation.
            </p>
            <p className="mt-3">
              YOU ARE SOLELY RESPONSIBLE FOR ALL DECISIONS YOU MAKE BASED ON INFORMATION PROVIDED BY THE SERVICE.
              YOU SHOULD CONSULT A LICENSED ATTORNEY IN YOUR STATE BEFORE TAKING ANY LEGAL ACTION, SENDING ANY
              LEGAL CORRESPONDENCE, OR MAKING ANY DECISION WITH LEGAL IMPLICATIONS.
            </p>
          </section>

          {/* 3 */}
          <section>
            <h2 className="text-white text-xl font-bold mb-3">3. Eligibility</h2>
            <p>
              You must be at least 18 years of age and legally capable of entering into binding contracts to use the
              Service. By using the Service you represent and warrant that you meet these requirements and that all
              information you provide is accurate and complete.
            </p>
          </section>

          {/* 4 */}
          <section>
            <h2 className="text-white text-xl font-bold mb-3">4. Account Registration and Security</h2>
            <p>
              You must create an account to access the Service. You agree to provide accurate, current, and complete
              information and to update that information as necessary. You are solely responsible for maintaining the
              confidentiality of your credentials and for all activity under your account. You must notify us immediately
              at {COMPANY_EMAIL} of any unauthorized access or security breach.
            </p>
          </section>

          {/* 5 */}
          <section>
            <h2 className="text-white text-xl font-bold mb-3">5. Subscription, Fees, and Cancellation</h2>
            <p>
              Access to the Service requires a paid subscription billed monthly (&quot;Subscription&quot;). Fees are charged in
              advance. All fees are in U.S. dollars. You authorize us to charge your payment method on a recurring basis
              until you cancel.
            </p>
            <p className="mt-3">
              You may cancel your Subscription at any time through your account settings or by contacting{' '}
              {COMPANY_EMAIL}. Cancellation takes effect at the end of the current billing period. We do not issue
              refunds for partial billing periods or unused time except as required by applicable law.
            </p>
            <p className="mt-3">
              We reserve the right to modify pricing with at least 30 days&apos; prior notice to your registered email
              address.
            </p>
          </section>

          {/* 6 */}
          <section>
            <h2 className="text-white text-xl font-bold mb-3">6. Acceptable Use</h2>
            <p>You agree not to use the Service to:</p>
            <ul className="list-disc pl-6 mt-3 space-y-2">
              <li>Violate any applicable law or regulation;</li>
              <li>Impersonate any person or entity or misrepresent your affiliation with any person or entity;</li>
              <li>Transmit any content that is unlawful, defamatory, harassing, abusive, or fraudulent;</li>
              <li>Attempt to gain unauthorized access to any part of the Service or its infrastructure;</li>
              <li>Use automated tools, scrapers, bots, or crawlers to access the Service without our written consent;</li>
              <li>Resell, sublicense, or commercialize the Service or its outputs without our written consent;</li>
              <li>Use the Service to provide legal advice to third parties;</li>
              <li>Interfere with or disrupt the integrity or performance of the Service.</li>
            </ul>
          </section>

          {/* 7 */}
          <section>
            <h2 className="text-white text-xl font-bold mb-3">7. Intellectual Property</h2>
            <p>
              The Service and all underlying technology, software, design, trademarks, and content created by the
              Company are owned by or licensed to the Company and are protected by applicable intellectual property
              laws. You are granted a limited, non-exclusive, non-transferable, revocable license to access and use
              the Service solely for your personal, non-commercial use in accordance with these Terms.
            </p>
            <p className="mt-3">
              AI-generated outputs produced through the Service are provided to you for your personal use. You may use,
              modify, and send letter templates generated for your own debt-related matters. You may not resell or
              redistribute Service outputs.
            </p>
          </section>

          {/* 8 */}
          <section>
            <h2 className="text-white text-xl font-bold mb-3">8. Third-Party Services</h2>
            <p>
              The Service uses third-party AI and infrastructure providers. We do not control and are not responsible
              for the accuracy, availability, or content of third-party services. Your use of any third-party service
              is governed by that service&apos;s own terms and privacy policy.
            </p>
          </section>

          {/* 9 */}
          <section>
            <h2 className="text-white text-xl font-bold mb-3">9. Privacy</h2>
            <p>
              Your use of the Service is also governed by our{' '}
              <Link href="/privacy" className="text-teal-400 underline hover:text-teal-300">
                Privacy Policy
              </Link>
              , which is incorporated into these Terms by reference. By using the Service you consent to the data
              practices described in the Privacy Policy.
            </p>
          </section>

          {/* 10 */}
          <section>
            <h2 className="text-white text-xl font-bold mb-3">10. Disclaimer of Warranties</h2>
            <p>
              THE SERVICE IS PROVIDED &quot;AS IS&quot; AND &quot;AS AVAILABLE&quot; WITHOUT WARRANTY OF ANY KIND. TO THE FULLEST EXTENT
              PERMITTED BY LAW, THE COMPANY EXPRESSLY DISCLAIMS ALL WARRANTIES, WHETHER EXPRESS, IMPLIED, STATUTORY,
              OR OTHERWISE, INCLUDING WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE,
              NON-INFRINGEMENT, TITLE, AND ACCURACY.
            </p>
            <p className="mt-3">
              WE DO NOT WARRANT THAT: (A) THE SERVICE WILL BE UNINTERRUPTED, ERROR-FREE, OR SECURE; (B) ANY
              INFORMATION OR CONTENT PROVIDED THROUGH THE SERVICE IS ACCURATE, COMPLETE, RELIABLE, CURRENT, OR
              SUITABLE FOR YOUR PURPOSES; (C) ANY LETTER TEMPLATE OR GUIDE WILL ACHIEVE A PARTICULAR OUTCOME; OR
              (D) THE SERVICE WILL MEET YOUR REQUIREMENTS.
            </p>
            <p className="mt-3">
              AI-generated content may contain errors, inaccuracies, or outdated information. You assume all risk
              associated with reliance on such content.
            </p>
          </section>

          {/* 11 */}
          <section>
            <h2 className="text-white text-xl font-bold mb-3">11. Limitation of Liability</h2>
            <p>
              TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT WILL THE COMPANY, ITS OFFICERS,
              DIRECTORS, EMPLOYEES, AGENTS, OR LICENSORS BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL,
              CONSEQUENTIAL, PUNITIVE, OR EXEMPLARY DAMAGES, INCLUDING LOSS OF PROFITS, REVENUE, DATA, GOODWILL,
              OR OTHER INTANGIBLE LOSSES, ARISING OUT OF OR IN CONNECTION WITH YOUR USE OF OR INABILITY TO USE
              THE SERVICE, REGARDLESS OF THE THEORY OF LIABILITY AND WHETHER OR NOT THE COMPANY HAS BEEN ADVISED
              OF THE POSSIBILITY OF SUCH DAMAGES.
            </p>
            <p className="mt-3">
              OUR TOTAL CUMULATIVE LIABILITY TO YOU FOR ALL CLAIMS ARISING OUT OF OR RELATING TO THESE TERMS OR
              THE SERVICE WILL NOT EXCEED THE GREATER OF (A) THE TOTAL AMOUNT YOU PAID TO THE COMPANY IN THE
              THREE (3) MONTHS IMMEDIATELY PRECEDING THE EVENT GIVING RISE TO THE CLAIM, OR (B) ONE HUNDRED
              U.S. DOLLARS ($100.00).
            </p>
            <p className="mt-3">
              SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF CERTAIN DAMAGES. IF THESE LAWS APPLY
              TO YOU, SOME OR ALL OF THE ABOVE EXCLUSIONS OR LIMITATIONS MAY NOT APPLY, AND YOU MAY HAVE
              ADDITIONAL RIGHTS.
            </p>
          </section>

          {/* 12 */}
          <section>
            <h2 className="text-white text-xl font-bold mb-3">12. Indemnification</h2>
            <p>
              You agree to indemnify, defend, and hold harmless the Company and its officers, directors, employees,
              agents, and licensors from and against any claims, liabilities, damages, judgments, awards, losses,
              costs, expenses, and fees (including reasonable attorneys&apos; fees) arising out of or relating to: (a)
              your use of or inability to use the Service; (b) your violation of these Terms; (c) your violation of
              any applicable law or the rights of any third party; or (d) any content you submit or transmit
              through the Service.
            </p>
          </section>

          {/* 13 */}
          <section>
            <h2 className="text-white text-xl font-bold mb-3">13. Termination</h2>
            <p>
              We may suspend or terminate your access to the Service at any time, with or without notice, for any
              reason, including if we reasonably believe you have violated these Terms. Upon termination, your right
              to access the Service ceases immediately. Sections 2, 7, 10, 11, 12, 14, 15, and 16 survive
              termination.
            </p>
          </section>

          {/* 14 */}
          <section>
            <h2 className="text-white text-xl font-bold mb-3">14. Governing Law</h2>
            <p>
              These Terms are governed by and construed in accordance with the laws of the State of{' '}
              {GOVERNING_STATE}, without regard to its conflict-of-law principles, except as modified by
              Section 15 (Arbitration). To the extent any dispute is not subject to arbitration, you consent to
              the exclusive personal jurisdiction of the state and federal courts located in {GOVERNING_STATE}.
            </p>
          </section>

          {/* 15 — THE ARBITRATION SECTION */}
          <section>
            <h2 className="text-white text-xl font-bold mb-3 border-b border-white/10 pb-3">
              15. Binding Arbitration and Class Action Waiver
            </h2>
            <p className="text-yellow-300 text-sm font-semibold mb-4">
              PLEASE READ THIS SECTION CAREFULLY. IT AFFECTS YOUR LEGAL RIGHTS, INCLUDING YOUR RIGHT TO FILE A
              LAWSUIT IN COURT AND YOUR RIGHT TO A JURY TRIAL.
            </p>

            <div className="space-y-5">
              <div>
                <h3 className="text-white font-semibold mb-2">15.1 Mutual Agreement to Arbitrate</h3>
                <p>
                  YOU AND THE COMPANY MUTUALLY AGREE THAT ANY AND ALL DISPUTES, CLAIMS, OR CONTROVERSIES
                  ARISING OUT OF OR RELATING TO THESE TERMS, THE SERVICE, THE COMPANY&apos;S PRIVACY POLICY, OR
                  YOUR RELATIONSHIP WITH THE COMPANY — WHETHER BASED IN CONTRACT, TORT, STATUTE, FRAUD,
                  MISREPRESENTATION, OR ANY OTHER LEGAL THEORY — WILL BE RESOLVED EXCLUSIVELY THROUGH FINAL
                  AND BINDING INDIVIDUAL ARBITRATION, EXCEPT AS SET FORTH IN SECTION 15.6.
                </p>
                <p className="mt-2">
                  This arbitration agreement applies to all claims that arose before these Terms were in effect,
                  that arise now, or that may arise in the future, including claims of which you are not aware
                  at the time you agree to these Terms.
                </p>
              </div>

              <div>
                <h3 className="text-white font-semibold mb-2">15.2 Arbitration Rules and Administration</h3>
                <p>
                  Arbitration shall be administered by JAMS pursuant to its Consumer Arbitration Rules (the
                  &quot;JAMS Rules&quot;), as modified by these Terms. The JAMS Rules are available at{' '}
                  <span className="text-teal-400">www.jamsadr.com</span>. If JAMS is unavailable or unwilling
                  to administer the arbitration, the parties shall mutually agree on an alternative arbitration
                  provider. If the parties cannot agree, a court of competent jurisdiction will select the
                  provider.
                </p>
              </div>

              <div>
                <h3 className="text-white font-semibold mb-2">15.3 Delegation of Arbitrability</h3>
                <p>
                  The parties delegate to the arbitrator — and not to any court — exclusive authority to
                  resolve all disputes about the formation, existence, scope, validity, interpretation,
                  enforceability, waiver, or applicability of this arbitration agreement, including whether a
                  particular claim is subject to arbitration, with the sole exception of disputes about the
                  enforceability of the class action waiver in Section 15.4.
                </p>
              </div>

              <div>
                <h3 className="text-white font-semibold mb-2">15.4 Class Action and Representative Action Waiver</h3>
                <p>
                  TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, YOU AND THE COMPANY EACH WAIVE ANY RIGHT
                  TO BRING OR PARTICIPATE IN ANY CLASS, COLLECTIVE, COORDINATED, CONSOLIDATED, MASS,
                  REPRESENTATIVE, OR PRIVATE ATTORNEY GENERAL ACTION OR PROCEEDING, WHETHER IN ARBITRATION
                  OR IN COURT. THE ARBITRATOR MAY NOT CONSOLIDATE OR JOIN MORE THAN ONE PERSON&apos;S OR PARTY&apos;S
                  CLAIMS AND MAY NOT OTHERWISE PRESIDE OVER ANY FORM OF A CONSOLIDATED, REPRESENTATIVE, OR
                  CLASS PROCEEDING.
                </p>
                <p className="mt-2">
                  The enforceability of this class action waiver shall be determined exclusively by a court of
                  competent jurisdiction, not by an arbitrator. If this waiver is found unenforceable with
                  respect to any claim, that claim shall be severed and litigated in court while the remaining
                  claims proceed in arbitration.
                </p>
              </div>

              <div>
                <h3 className="text-white font-semibold mb-2">15.5 Jury Trial Waiver</h3>
                <p>
                  BY AGREEING TO ARBITRATE, BOTH PARTIES WAIVE THEIR CONSTITUTIONAL AND STATUTORY RIGHTS TO
                  GO TO COURT AND HAVE A TRIAL IN FRONT OF A JUDGE OR JURY. ARBITRATION PROCEDURES ARE
                  DIFFERENT FROM COURT PROCEDURES, AND DISCOVERY RIGHTS MAY BE MORE LIMITED IN ARBITRATION.
                </p>
              </div>

              <div>
                <h3 className="text-white font-semibold mb-2">15.6 Exceptions to Arbitration</h3>
                <p>Notwithstanding the foregoing, either party may seek relief in court for:</p>
                <ul className="list-disc pl-6 mt-2 space-y-1">
                  <li>
                    Claims for injunctive or equitable relief to prevent the actual or threatened
                    infringement, misappropriation, or violation of intellectual property rights;
                  </li>
                  <li>
                    Claims that may be brought in small claims court, provided they qualify and remain on an
                    individual basis only;
                  </li>
                  <li>
                    Any claim that applicable law expressly requires to be resolved in a judicial forum.
                  </li>
                </ul>
              </div>

              <div>
                <h3 className="text-white font-semibold mb-2">15.7 Pre-Arbitration Notice and Good-Faith Resolution</h3>
                <p>
                  Before initiating arbitration, the initiating party must provide the other party written
                  notice of the dispute (&quot;Notice of Dispute&quot;) by emailing{' '}
                  <span className="text-teal-400">{ARBITRATION_NOTICE_ADDRESS}</span> (for notices to the
                  Company) or your registered email address (for notices to you). The Notice of Dispute must
                  include: (a) the claimant&apos;s name and contact information; (b) a description of the nature
                  and basis of the claim; and (c) the specific relief sought.
                </p>
                <p className="mt-2">
                  The parties shall attempt to resolve the dispute in good faith for a period of sixty (60)
                  days following delivery of the Notice of Dispute. If the dispute is not resolved within
                  sixty (60) days, either party may proceed to file for arbitration.
                </p>
              </div>

              <div>
                <h3 className="text-white font-semibold mb-2">15.8 Opt-Out of Arbitration</h3>
                <p>
                  You may opt out of this arbitration agreement by sending written notice to{' '}
                  <span className="text-teal-400">{ARBITRATION_NOTICE_ADDRESS}</span> with the subject line
                  &quot;Arbitration Opt-Out&quot; within <strong className="text-white">thirty (30) days</strong> of
                  first creating an account or agreeing to these Terms (whichever is earlier). Your opt-out
                  notice must include your full name, email address associated with your account, and a
                  statement that you wish to opt out of arbitration.
                </p>
                <p className="mt-2">
                  If you opt out, neither party may require the other to participate in arbitration for any
                  dispute. All other terms remain in full force. Opting out will not affect your ability to
                  use the Service.
                </p>
              </div>

              <div>
                <h3 className="text-white font-semibold mb-2">15.9 Arbitration Fees and Costs</h3>
                <p>
                  The allocation of arbitration fees shall be governed by the applicable JAMS Rules. If your
                  claim does not exceed $10,000 USD, the Company will pay all JAMS filing, administration,
                  and arbitrator fees. If your claim exceeds $10,000 USD, the JAMS Rules will govern fee
                  allocation. Each party is responsible for its own attorneys&apos; fees, except where applicable
                  law permits recovery of attorneys&apos; fees.
                </p>
              </div>

              <div>
                <h3 className="text-white font-semibold mb-2">15.10 Location and Manner of Arbitration</h3>
                <p>
                  Unless you and the Company agree otherwise, arbitration will be conducted in {GOVERNING_STATE}{' '}
                  or, if you prefer, via telephone or videoconference. For claims under $25,000, arbitration
                  shall be conducted on the basis of written submissions only, unless the arbitrator determines
                  a hearing is necessary.
                </p>
              </div>

              <div>
                <h3 className="text-white font-semibold mb-2">15.11 Mass Arbitration Procedures</h3>
                <p>
                  If twenty-five (25) or more similar claims are filed against the Company by the same or
                  coordinated counsel within a 180-day period (&quot;Mass Arbitration&quot;), the parties agree to the
                  following batching procedure: claims will be resolved in batches of no more than fifty (50)
                  claims per batch, with the first batch proceeding first and subsequent batches proceeding
                  sequentially. The parties will work with JAMS to implement this procedure. If JAMS is
                  unwilling to administer claims under this procedure, a different provider shall be selected
                  pursuant to Section 15.2.
                </p>
              </div>

              <div>
                <h3 className="text-white font-semibold mb-2">15.12 Confidentiality</h3>
                <p>
                  The arbitration proceeding and all related filings, submissions, orders, decisions, and
                  awards shall be kept confidential by all parties, except as necessary to prepare for or
                  conduct the arbitration hearing, to seek judicial enforcement of an award, or as required
                  by applicable law.
                </p>
              </div>

              <div>
                <h3 className="text-white font-semibold mb-2">15.13 Severability</h3>
                <p>
                  If any portion of this Section 15 is found to be unenforceable, that portion will be
                  severed and the remaining portions will continue in full force and effect, except that if
                  the class action waiver in Section 15.4 is found unenforceable in whole or in part, this
                  entire Section 15 will be unenforceable with respect to that claim only.
                </p>
              </div>

              <div>
                <h3 className="text-white font-semibold mb-2">15.14 Future Changes to Arbitration Agreement</h3>
                <p>
                  If the Company makes any material change to this arbitration agreement, you may reject the
                  change by sending written notice to {ARBITRATION_NOTICE_ADDRESS} within thirty (30) days of
                  the change taking effect. If you reject a change, the arbitration agreement in effect at the
                  time you first accepted these Terms will apply.
                </p>
              </div>
            </div>
          </section>

          {/* 16 */}
          <section>
            <h2 className="text-white text-xl font-bold mb-3">16. General Provisions</h2>
            <div className="space-y-4">
              <div>
                <h3 className="text-white font-semibold mb-1">16.1 Entire Agreement</h3>
                <p>
                  These Terms, together with the Privacy Policy, constitute the entire agreement between you
                  and the Company regarding the Service and supersede all prior agreements and understandings.
                </p>
              </div>
              <div>
                <h3 className="text-white font-semibold mb-1">16.2 Modifications</h3>
                <p>
                  We may modify these Terms at any time by posting the revised Terms on the Service and
                  updating the Effective Date. Your continued use of the Service after the effective date
                  of modifications constitutes acceptance of the revised Terms.
                </p>
              </div>
              <div>
                <h3 className="text-white font-semibold mb-1">16.3 Waiver</h3>
                <p>
                  No waiver of any provision of these Terms will be deemed a further or continuing waiver of
                  such provision or any other provision. Our failure to enforce any right or provision will
                  not constitute a waiver.
                </p>
              </div>
              <div>
                <h3 className="text-white font-semibold mb-1">16.4 Severability</h3>
                <p>
                  If any provision of these Terms (other than as specified in Section 15.13) is held invalid,
                  illegal, or unenforceable, the remaining provisions will continue in full force and effect.
                </p>
              </div>
              <div>
                <h3 className="text-white font-semibold mb-1">16.5 Assignment</h3>
                <p>
                  You may not assign or transfer these Terms or any rights or obligations hereunder without
                  our prior written consent. The Company may freely assign these Terms without restriction.
                  Any purported assignment in violation of this section is void.
                </p>
              </div>
              <div>
                <h3 className="text-white font-semibold mb-1">16.6 Force Majeure</h3>
                <p>
                  The Company will not be liable for any failure or delay in performance resulting from causes
                  beyond our reasonable control, including acts of God, war, terrorism, natural disasters,
                  government action, or third-party infrastructure failures.
                </p>
              </div>
              <div>
                <h3 className="text-white font-semibold mb-1">16.7 Contact</h3>
                <p>
                  Questions about these Terms may be directed to:{' '}
                  <a href={`mailto:${COMPANY_EMAIL}`} className="text-teal-400 underline hover:text-teal-300">
                    {COMPANY_EMAIL}
                  </a>
                </p>
              </div>
            </div>
          </section>

        </div>
      </main>

      {/* Footer */}
      <footer className="border-t border-white/10 py-8 px-4">
        <div className="max-w-6xl mx-auto flex flex-col sm:flex-row items-center justify-between gap-4">
          <div className="flex items-center gap-2">
            <div className="w-6 h-6 bg-teal-400 rounded-lg flex items-center justify-center">
              <Zap className="w-3.5 h-3.5 text-navy-200" />
            </div>
            <span className="text-white/60 text-sm font-medium">DebtCoach AI</span>
          </div>
          <p className="text-white/30 text-xs text-center">
            Not legal advice · Educational purposes only · Not a law firm · No attorney-client relationship
          </p>
          <div className="flex gap-4 text-white/40 text-xs">
            <Link href="/privacy" className="hover:text-white/70">Privacy</Link>
            <Link href="/terms" className="hover:text-white/70">Terms</Link>
            <a href={`mailto:${COMPANY_EMAIL}`} className="hover:text-white/70">Support</a>
          </div>
        </div>
      </footer>
    </div>
  )
}
