/**
 * DebtCoach AI — PDF letter generator
 * Produces a properly formatted, print-ready formal letter PDF using jsPDF.
 */

export async function downloadLetterPDF(letterText: string, letterType: string, creditorName: string) {
  const { jsPDF } = await import('jspdf')
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'letter' })

  const pageW = doc.internal.pageSize.getWidth()
  const pageH = doc.internal.pageSize.getHeight()
  const margin = 25
  const contentW = pageW - margin * 2
  let y = margin

  // ── Header bar ──────────────────────────────────────────────────────────────
  doc.setFillColor(15, 40, 60)
  doc.rect(0, 0, pageW, 12, 'F')
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(8)
  doc.setTextColor(100, 220, 200)
  doc.text('DebtCoach AI  ·  AI-Powered Debt Relief Letters', margin, 8)
  doc.setTextColor(180, 180, 180)
  doc.text('debtcoach.ai', pageW - margin, 8, { align: 'right' })

  y = 22

  // ── Letter type label ────────────────────────────────────────────────────────
  const typeLabel = letterType.replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase())
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(8)
  doc.setTextColor(120, 120, 120)
  doc.text(`RE: ${typeLabel}  ·  ${creditorName}`, margin, y)
  y += 3

  // ── Horizontal rule ──────────────────────────────────────────────────────────
  doc.setDrawColor(200, 200, 200)
  doc.setLineWidth(0.3)
  doc.line(margin, y, pageW - margin, y)
  y += 8

  // ── Body text ────────────────────────────────────────────────────────────────
  doc.setFont('courier', 'normal')
  doc.setFontSize(9.5)
  doc.setTextColor(30, 30, 30)

  const paragraphs = letterText.split('\n')

  for (const para of paragraphs) {
    if (para.trim() === '') {
      y += 4
      continue
    }

    // Check if this is a header-like line (all caps, short line)
    const isHeader = para.trim().length < 60 && para.trim() === para.trim().toUpperCase() && /[A-Z]{3,}/.test(para)

    if (isHeader) {
      doc.setFont('courier', 'bold')
      doc.setFontSize(9.5)
    } else {
      doc.setFont('courier', 'normal')
      doc.setFontSize(9.5)
    }

    const lines = doc.splitTextToSize(para, contentW)

    for (const line of lines) {
      // New page if needed
      if (y + 6 > pageH - 20) {
        doc.addPage()
        y = margin

        // Continuation header
        doc.setFillColor(15, 40, 60)
        doc.rect(0, 0, pageW, 12, 'F')
        doc.setFont('helvetica', 'bold')
        doc.setFontSize(8)
        doc.setTextColor(100, 220, 200)
        doc.text('DebtCoach AI  ·  Letter Continued', margin, 8)
        doc.setTextColor(30, 30, 30)
        y = 22
        doc.setFont('courier', 'normal')
        doc.setFontSize(9.5)
      }

      doc.text(line, margin, y)
      y += 5
    }
  }

  // ── Footer ───────────────────────────────────────────────────────────────────
  const totalPages = (doc as any).internal.getNumberOfPages()
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i)
    doc.setFillColor(245, 245, 245)
    doc.rect(0, pageH - 10, pageW, 10, 'F')
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(7)
    doc.setTextColor(150, 150, 150)
    doc.text(`Generated by DebtCoach AI  ·  ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`, margin, pageH - 4)
    doc.text(`Page ${i} of ${totalPages}`, pageW - margin, pageH - 4, { align: 'right' })
  }

  // ── Save ─────────────────────────────────────────────────────────────────────
  const filename = `${letterType.replace(/_/g, '-')}-${creditorName.replace(/\s+/g, '-').toLowerCase()}.pdf`
  doc.save(filename)
}
